apiVersion: v1
kind: Service
metadata:
  name: laxya-portfolio-service
spec:
  type: NodePort
  selector:
    app: laxya-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
